# Pywal colours
include ~/.cache/wal/colors-kitty.conf

# Transparency + blur
background_opacity 0.85
background_blur 20

# Font
font_family 0xProto Nerd Font
font_size 13.0

# General
confirm_os_window_close 0
