# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                    Autostart Configuration                  ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

source = ~/.config/hypr/config/defaults.conf

# Autostart
exec-once = /usr/bin/awww-daemon
exec-once = ~/.config/hypr/scripts/restore-theme.sh
exec-once = pkill -SIGUSR2 waybar || waybar &
exec-once = fcitx5 -d
exec-once = mako
exec-once = nm-applet --indicator
exec-once = bash -c "mkfifo /tmp/$HYPRLAND_INSTANCE_SIGNATURE.wob && tail -f /tmp/$HYPRLAND_INSTANCE_SIGNATURE.wob | wob"
exec-once = /usr/lib/polkit-kde-authentication-agent-1
exec-once = easyeffects --gapplication-service
exec-once = ncpamixer


# Slow app launch fix (Modern Hyprland standard)
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

# Idle configuration
exec-once = $idlehandler
