# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                    Autostart Configuration                  ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

source = ~/.config/hypr/config/defaults.conf

# 1. Clean the environment and fix logout lag
exec-once = ~/.config/hypr/scripts/init-session.sh

# 2. Core System Services & Authentication
exec-once = /usr/lib/polkit-kde-authentication-agent-1
exec-once = systemctl --user start hyprpolkitagent
exec-once = hypridle

# 3. The Desktop Shell (Bar and Notifications)
# We launch Waybar here so it has a clean DBus environment
exec-once = sleep 3 && ~/.config/hypr/scripts/reload-waybar.sh
exec-once = nm-applet --indicator
exec-once = sleep 2 && nm-applet --indicator
exec-once = sleep 2.5 && swaync
exec-once = fcitx5 -d
exec-once = swaync

# 4. Audio, Haptics & Input Tools
exec-once = easyeffects --gapplication-service
exec-once = ncpamixer
exec-once = bash -c "mkfifo /tmp/$HYPRLAND_INSTANCE_SIGNATURE.wob && tail -f /tmp/$HYPRLAND_INSTANCE_SIGNATURE.wob | wob"

# 5. Theming (Executed last so apps are ready to receive colors)
exec-once = /usr/bin/awww-daemon
exec-once = ~/.config/hypr/scripts/restore-theme.sh
