# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                     Monitor Configuration                   ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

# Main Monitor (360Hz) - 10-bit SDR
monitor = DP-1, 2560x1440@360, 0x0, 1, bitdepth, 10

# Second Monitor (240Hz) - 10-bit SDR
monitor = DP-2, 2560x1440@240, 2560x0, 1, bitdepth, 10

# Force Electron apps (Discord, VS Code, etc) to use Wayland
env = ELECTRON_OZONE_PLATFORM_HINT, auto

misc {
    vrr = 2 # 0: off, 1: on, 2: fullscreen only
}
